[package]
name = "matrix"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
eframe = "0.32.0"
matrix-sdk = "0.13.0"
tokio = { version = "1", features = ["rt-multi-thread"] }
tracing-subscriber = "0.3.19"
url = "2.5.4"
